/*

    DO NOT MODIFY THIS FILE!

    THIS FILE IS GENERATED BY JP.Notek.AtomicSoup.Editor.AtomSourceGenerator.
*/
using JP.Notek.AtomicSoup;
using UdonSharp;
using UnityEngine;
using VRC.SDK3.Data;
using VRC.SDKBase;
using VRC.Udon.Common;

namespace AtomicSoupSample.ExampleModel
{
    [UdonSharpProgramAsset]
    public class SyncAdapterGenerated : AtomSubscriberForSync
    {
        [DIInject, SubscribeAtom] public SyncValue1Atom SyncValue1;
        [DIInject, SubscribeAtom] public SyncValue2Atom SyncValue2;
        [UdonSynced] public bool SyncValue1Synced;
        [UdonSynced] public bool SyncValue2Synced;
        protected override void ReflectAtomToUdonSynced()
        {
            SyncValue1Synced = SyncValue1.Value;
            SyncValue2Synced = SyncValue2.Value;
        }

        protected override void ReflectUdonSyncedToAtom()
        {
            SyncValue1.Set(SyncValue1Synced);
            SyncValue2.Set(SyncValue2Synced);
        }
    }
}